# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2013, Numenta, Inc.  Unless you have an agreement
# with Numenta, Inc., for a separate license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------


## This file defines parameters for a prediction experiment.

###############################################################################
#                                IMPORTANT!!!
# This params file is dynamically generated by the RunExperimentPermutations
# script. Any changes made manually will be over-written the next time
# RunExperimentPermutations is run!!!
###############################################################################


from nupic.frameworks.opf.expdescriptionhelpers import importBaseDescription

# the sub-experiment configuration
config ={
  'aggregationInfo' : {'seconds': 0, 'fields': [], 'months': 0, 'days': 0, 'years': 0, 'hours': 0, 'microseconds': 0, 'weeks': 0, 'minutes': 0, 'milliseconds': 0},
  'modelParams' : {'sensorParams': {'encoders': {'_classifierInput': {'maxval': 74, 'classifierOnly': True, 'minval': 0, 'clipInput': True, 'n': 33, 'fieldname': 'hourly_traffic_count', 'w': 21, 'type': 'ScalarEncoder'}, u'timestamp_dayOfWeek': {'dayOfWeek': (21, 6), 'name': 'timestamp', 'fieldname': 'timestamp', 'type': 'DateEncoder'}, u'timestamp_timeOfDay': {'name': 'timestamp', 'fieldname': 'timestamp', 'timeOfDay': (21, 5.657675158412203), 'type': 'DateEncoder'}, u'hourly_traffic_count': {'maxval': 74, 'name': 'hourly_traffic_count', 'clipInput': True, 'minval': 0, 'n': 118, 'fieldname': 'hourly_traffic_count', 'w': 21, 'type': 'ScalarEncoder'}, u'timestamp_weekend': None}}, 'spParams': {'synPermInactiveDec': 0.09994522481980617}, 'tpParams': {'minThreshold': 9, 'activationThreshold': 12, 'pamLength': 1}, 'clParams': {'alpha': 0.0001}},

}

mod = importBaseDescription('../description.py', config)
locals().update(mod.__dict__)
